const CONFIG = {
    introTitle: 'Nga nè!',
    introDesc: `Phước hỏi Nga phải trả lời thật lòng đấy😁😁`,
    btnIntro: 'hehe',
    title: 'Nhớ là thật lòng đấy nhé',
    desc: 'Nga có đang thích tui không đó?😁 ',
    btnYes: 'Có nhen <3',
    btnNo: 'Không :3',
    question:'Ơ tại sao thích tui thế 😁😁',
    btnReply: 'Gửi cho Phước <3',
    reply: 'Tại Phước đáng yêu quá đó',
    mess: 'Tui biết mà 🥰. Yêu Nga nhiều nhiều 😘😘',
    messDesc: 'Cái quan trọng nè ngày mai Nga thi tốt nhé <3',
    btnAccept: 'Okeeee la <3',
}
